# Generated by Django 6.0 on 2026-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('documents', models.FileField(upload_to='documents/')),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
